### ISSUE TITLE
segment_web_sessions__initial drops data on incremental runs

### ISSUE THREAD

**Issue by samkessaram** [dbt-labs/segment#62]
### Describe the bug

During incremental runs, the `segment_web_sessions__initial` model excludes page views from `segment_web_page_views__sessionized` that fall outside of the bounds of the `segment_sessionization_trailing_window`. 

The result is that any session calculations downstream of here will be based on incomplete data. 

### Steps to reproduce

Run:
`dbt run -m  +segment_web_sessions --full-refresh`
`dbt run -m  +segment_web_sessions`

### Expected results

This depends on your pages data, but this should return 0. (i.e. every page should be included in it's aggregated session.)
```
select 
    count(*) 
from segment_web_page_views__sessionized pages
left join segment_web_sessions sessions on pages.session_id = sessions.session_id
where pages.tstamp < sessions.session_start_tstamp
```

### Actual results

Some page views aren't included in the aggregated session data.

### Screenshots and log output

Example:

```
select 
    pages.tstamp,
    sessions.session_start_tstamp,
    sessions.session_end_tstamp
from segment_web_page_views__sessionized pages
left join segment_web_sessions sessions on pages.session_id = sessions.session_id
where pages.tstamp < sessions.session_start_tstamp
```

|TSTAMP|SESSION_START_TSTAMP|SESSION_END_TSTAMP|
|---|---|---|
|2020-11-03 12:13:29.179|2020-11-03 12:15:18.752|2020-11-03 12:15:24.659|
|2020-11-03 12:13:51.331|2020-11-03 12:15:18.752|2020-11-03 12:15:24.659|
|2020-11-03 12:13:52.435|2020-11-03 12:15:18.752|2020-11-03 12:15:24.659|

The page views are at 12:13, but the session isn't said to "start" until 12:15! 🤯 

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
  - package: fishtown-analytics/segment
    version: 0.5.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
```

**The operating system you're using:**
macOS Catalina

**The output of `python --version`:**
`Python 2.7.16`

### Additional context

The issue seems to be arising from here: https://github.com/fishtown-analytics/segment/blob/master/models/sessionization/segment_web_sessions__initial.sql#L45

Rather than just selecting page views that occur in that window, we should select all page views for any _sessions_ that intersect with the window.

### Are you interested in contributing the fix?

PR: https://github.com/fishtown-analytics/segment/pull/64

**Comment by jtcohen6** [comment]
Hey @samkessaram, thanks for the detailed writeup, and for the corresponding PRs.

If you haven't already, I'd encourage you to read [this discourse post](https://discourse.getdbt.com/t/on-the-limits-of-incrementality/303) about the various trade-offs involved in incremental modeling.

This package takes the "close enough & performant" approach, rather than "always correct & slow." Based on some empirical research, a 72-hour trailing window tends to be sufficient to incorporate 99.9% of events, at the cost of missing 0.01% of late-arriving events. We're intentionally trading off absolute correctness for orders-of-magnitude better performance during incremental runs, by scanning the last 3 days of data instead of the entire table. We "catch up" to absolute correctness with a `--full-refresh` run once per week.

That's especially relevant on databases like BigQuery, where the cost is directly related to the amount of data scanned, but it's also a big help on databases like Redshift and Snowflake. If we need to filter on both the date (new page views) and the `session_id` (old page views from the same session), should we sort/cluster by the date (to speed up filter) or by `session_id` (to speed up implicit join criteria)?

At the same time, we know that some users will want to look back further—or they may not care much about late-arriving events at all. For that reason, `segment_sessionization_trailing_window` is a configurable `var` that can be overridden in the user's project or on the CLI.

Check out this related PR from the Snowplow package: https://github.com/fishtown-analytics/snowplow/pull/71. Previously, we had used an "always correct & slow" approach, but _it just wasn't worth it._ By default, it was preferable to have a speedier incremental build, with a configurable look-back window, that could be 99.9% right at scale and catch up once a week.

I think there may still be code we could improve here. For instance, we could check to see if an event is late-arriving beyond its acceptable window, such that we should exclude it from the incremental build entirely and prevent it from overwriting the existing page views and sessions.

All of that said, if in your own project, you need to implement an "always correct & slow" lookback to capture _every_ page view for _every_ session, no matter how late-arriving its component events, you absolutely can by disabling the package's version of `segment_web_sessions__initial` and adding your own model by the same name in its place:
```yml
models:
  segment:
    sessionization:
      segment_web_sessions__initial:
        +enabled: false
```

**Comment by samkessaram** [comment]
@jtcohen6 Thanks for the detailed response, what you're saying make sense, especially in the broader context. I had read that discourse post a while ago, but the refresher was definitely helpful. I think your periodic `--full-refresh` strategy is a good way to go for us. Thanks again, much appreciated. 👍
